export const QUESTION_IDS = {
  LOCATION: 1,
  HOUSEHOLD_SIZE: 2,
  HOUSING_TYPE: 3,
  APARTMENT_SIZE: 4,
  MOUNTING_LOCATION: 5,
  ORIENTATION: 6,
  BALCONY_SIZE: 7,
  SHADING: 8,
  APPLIANCES: 9,
  CONSUMPTION: 10,
  BUDGET: 11,
  ECO_IMPORTANCE: 12,
} as const;

export type QuestionId = typeof QUESTION_IDS[keyof typeof QUESTION_IDS];

export const VALID_QUESTION_IDS = Object.values(QUESTION_IDS);

export const TOTAL_QUESTIONS = VALID_QUESTION_IDS.length;
